Cheng-Kun-Liu/Quickly-Use-Jetpack-Compose

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/laomuji666/compose/quickly/HiltApplication.kt
- app/src/main/java/com/laomuji666/compose/quickly/MainActivity.kt
- app/src/main/java/com/laomuji666/compose/quickly/MainViewModel.kt
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
- build-logic/convention/src/main/kotlin/util/ProjectExtensions.kt
- build-logic/gradle.properties
- build-logic/settings.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
> 以Plugin的方式引入Hilt依赖

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/laomuji666/compose/HiltApplication.kt
- app/src/main/java/com/laomuji666/compose/MainActivity.kt
- app/src/main/java/com/laomuji666/compose/MainViewModel.kt
- app/src/main/java/com/laomuji666/compose/navigation/NavigationHost.kt
- app/src/main/java/com/laomuji666/compose/navigation/NavigationOption.kt
- core-ui/build.gradle.kts
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloNavigation.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloViewModel.kt
- gradle/libs.versions.toml
> 添加Navigation导航

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/ErrorView.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/LoadingDialog.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpScreen.kt
> ktor等待响应,网络异常处理.

- app/src/main/java/com/laomuji666/compose/SimpleFirebaseMessagingService.kt
- core-logic/build.gradle.kts
- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/http/HttpService.kt
- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/notification/FirebaseNotification.kt
- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/util/Log.kt
- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/util/Toast.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpViewModel.kt
> 添加简单的Toast,Log工具

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/ArrowLeft.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/ArrowRight.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Checked.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Radiochecked.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Select.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/TopBarAdd.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/TopBarMenu.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/TopBarSearch.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Unselect.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableCheckRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableClickRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRadioRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableSwitchRow.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
> We设计系统单选,多选,开关

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeDimens.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeTheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableCheckRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableClickRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRadioRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableSwitchRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTopBar.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
> We设计系统:统一尺寸,统一TableRow

- app/src/main/java/com/laomuji666/compose/navigation/NavigationHost.kt
- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/http/HttpRepository.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeActionSheet.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeButton.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeNavigationBar.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableCheckRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableClickRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRadioRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableSwitchRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeToast.kt
- feature/firebase/src/main/kotlin/com/laomuji666/compose/feature/hello/FirebaseNavigation.kt
- feature/firebase/src/main/kotlin/com/laomuji666/compose/feature/hello/FirebaseScreen.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpNavigation.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpScreen.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpUiState.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpViewModel.kt
- res/src/main/res/values/strings.xml
> We设计系统:更新颜色

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeDimens.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeTheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeScaffold.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableClickRow.kt
- feature/firebase/src/main/kotlin/com/laomuji666/compose/feature/hello/FirebaseScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloSelectEnum.kt
- feature/http/src/main/kotlin/com/laomuji666/compose/feature/hello/HttpScreen.kt
- res/src/main/res/values/strings.xml
> 修复屏幕适配写反的问题

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColors.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeDimens.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeTheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Done.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/icons/Error.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeActionSheet.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeButton.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRowOutline.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableSwitchRow.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeToast.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/WidgetScreen.kt
> We设计系统重构:颜色值,组件颜色,点击效果

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColors.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeTheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeActionSheet.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRow.kt
- feature/firebase/src/main/kotlin/com/laomuji666/compose/feature/hello/FirebaseScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/WidgetScreen.kt
> We设计系统重构:细节补充

- core-ui/build.gradle.kts
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/launcher/SelectMobileLauncher.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
- gradle/libs.versions.toml
- res/src/main/res/values/strings.xml
> 调用谷歌认证插件让用户选择自己的手机号

- core-logic/src/main/kotlin/com/laomuji666/compose/core/logic/repository/contacts/ContactInfo.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeDimens.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeTypography.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeActionSheet.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableTitle.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTopNavigationBar.kt
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/contacts/ContactsScreen.kt
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/contacts/ContactsScreenUiState.kt
> 联系人右侧点击快速跳转

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeContactItem.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRow.kt
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/AiChatScreen.kt
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/contacts/ContactsScreen.kt
> 修复WeTableRow长按阴影重叠问题

- core-logic/common/src/main/kotlin/com/laomuji666/compose/core/logic/common/Log.kt
- core-logic/repository/src/main/kotlin/com/laomuji666/compose/core/logic/repository/module/contacts/ContactInfo.kt
- core-logic/repository/src/main/kotlin/com/laomuji666/compose/core/logic/repository/module/contacts/ContactsRepository.kt
- core-ui/build.gradle.kts
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeContactItem.kt
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/contacts/ContactsScreen.kt
- gradle/libs.versions.toml
> 加载网络图片改为coil,启用磁盘缓存.

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/WeDimens.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableInput.kt
- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/we/widget/WeTableRow.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/ExampleScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/HelloScreen.kt
- feature/hello/src/main/kotlin/com/laomuji666/compose/feature/hello/WidgetScreen.kt
> WeTableInput

- core-ui/src/main/kotlin/com/laomuji666/compose/core/ui/ViewModelExtension.kt
> 默认的combine参数太少了,增加一些.

- core-logic/authenticate/src/main/kotlin/com/laomuji666/compose/core/logic/authenticate/biometric/BiometricAuthenticate.kt
- core-logic/authenticate/src/main/kotlin/com/laomuji666/compose/core/logic/authenticate/biometric/DefaultBiometricAuthenticate.kt
- feature/biometric/src/main/kotlin/com/laomuji666/compose/feature/biometric/BiometricScreen.kt
- feature/biometric/src/main/kotlin/com/laomuji666/compose/feature/biometric/BiometricScreenViewModel.kt
- res/src/main/res/values/strings.xml
> 生物认证,未设置时跳转设置.

- core-launcher/src/main/kotlin/com/laomuji666/compose/launcher/PermissionUtil.kt
- core-logic/location/src/main/kotlin/com/laomuji666/compose/core/logic/location/DefaultLocator.kt
- core-logic/location/src/main/kotlin/com/laomuji666/compose/core/logic/location/Locator.kt
- feature/chat/build.gradle.kts
- feature/chat/src/main/kotlin/com/laomuji666/compose/feature/chat/me/MeScreen.kt
- feature/demo/src/main/kotlin/com/laomuji666/compose/feature/demo/device/DeviceDemoScreen.kt
- feature/demo/src/main/kotlin/com/laomuji666/compose/feature/demo/device/DeviceDemoScreenViewModel.kt
- feature/firebase/build.gradle.kts
- feature/firebase/src/main/kotlin/com/laomuji666/compose/feature/firebase/FirebaseScreen.kt
> #100 统一权限处理

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/laomuji666/compose/WebViewActivity.kt
- app/src/main/java/com/laomuji666/compose/navigation/NavigationHost.kt
- feature/webview/src/main/kotlin/com/laomuji666/compose/feature/webview/CustomWebChromeClient.kt
- feature/webview/src/main/kotlin/com/laomuji666/compose/feature/webview/CustomWebViewClient.kt
- feature/webview/src/main/kotlin/com/laomuji666/compose/feature/webview/WebViewScreen.kt
- feature/webview/src/main/kotlin/com/laomuji666/compose/feature/webview/WebViewScreenUtil.kt
- res/src/main/res/values/strings.xml
> WebView屏幕示例,浏览器manifest.

- core-logic/language/src/main/kotlin/com/laomuji888/compose/core/logic/AppLanguages.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/ComposeExtension.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/NavigationOption.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/WeIndication.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/screen/SlideActivity.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/screen/SlideNavigation.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/theme/Theme.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/BannerView.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/LoadingDialog.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/banner/Banner.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/banner/BannerState.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/banner/BannerType.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/WeTheme.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/WeThemeCache.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/animated/AnimatedSlideFromBottom.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeColorSchemeBlue.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeColorSchemeDark.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeColorSchemeLight.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeColors.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/colorscheme/WeThemeColorType.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/widget/actionsheet/WeActionSheetDialog.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/we/widget/toast/WeToast.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/contacts/ContactsScreen.kt
- feature/demo/src/main/kotlin/com/laomuji888/compose/feature/main/ui/UiDemoScreen.kt
- feature/webview/src/main/kotlin/com/laomuji888/compose/feature/webview/WebViewScreen.kt
- feature/youtubedl/src/main/kotlin/com/laomuji888/compose/feature/youtubedl/AddDownloadDialog.kt
> #122 解决弹窗屏幕适配失效的问题

- app/src/main/kotlin/com/laomuji888/compose/navigation/NavigationHost.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/NavigationExtension.kt
- core-ui/src/main/kotlin/com/laomuji888/compose/core/ui/view/banner/Banner.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/AiChatScreen.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/AiChatScreenAction.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/AiChatScreenRoute.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/AiChatScreenViewModel.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/chat/ChatScreen.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/chat/ChatScreenAction.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/chat/ChatScreenRoute.kt
- feature/chat/src/main/kotlin/com/laomuji888/compose/feature/chat/chat/ChatScreenViewModel.kt
- feature/demo/src/main/kotlin/com/laomuji888/compose/feature/main/MainScreen.kt
- feature/demo/src/main/kotlin/com/laomuji888/compose/feature/main/MainScreenRoute.kt
- feature/demo/src/main/kotlin/com/laomuji888/compose/feature/main/MainScreenViewModel.kt
- feature/demo/src/main/kotlin/com/laomuji888/compose/feature/main/ui/UiDemoScreen.kt
- feature/firebase/src/main/kotlin/com/laomuji888/compose/feature/firebase/FirebaseScreen.kt
- feature/firebase/src/main/kotlin/com/laomuji888/compose/feature/firebase/FirebaseScreenRoute.kt
- feature/http/src/main/kotlin/com/laomuji888/compose/feature/http/HttpScreen.kt
- feature/http/src/main/kotlin/com/laomuji888/compose/feature/http/HttpScreenRoute.kt
- feature/language/src/main/kotlin/com/laomuji888/compose/feature/language/LanguageScreen.kt
- feature/language/src/main/kotlin/com/laomuji888/compose/feature/language/LanguageScreenAction.kt
- feature/language/src/main/kotlin/com/laomuji888/compose/feature/language/LanguageScreenRoute.kt
- feature/language/src/main/kotlin/com/laomuji888/compose/feature/language/LanguageScreenViewModel.kt
> 导航改为单一数据源,由ViewModel控制.

- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/theme/Theme.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/colorscheme/WeColorScheme.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/colorscheme/WeThemeColorType.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/widget/theme/WeThemeTypeSettingDialog.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/widget/topbar/WeTopBar.kt
- feature/date/src/main/kotlin/com/laomuji1999/compose/feature/date/DateScreen.kt
- res/src/main/res/values-ar/strings.xml
- res/src/main/res/values-bn/strings.xml
- res/src/main/res/values-en/strings.xml
- res/src/main/res/values-es/strings.xml
- res/src/main/res/values-zh-rCN/strings.xml
- res/src/main/res/values-zh-rTW/strings.xml
- res/src/main/res/values/strings.xml
> 颜色系统支持动态取色

- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/theme/Theme.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/cache/WeCache.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/cache/WeCacheTypography.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/typography/WeTextStyles.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/typography/WeTypography18.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/typography/WeTypography19.kt
- core-ui/src/main/kotlin/com/laomuji1999/compose/core/ui/we/typography/WeTypography20.kt
- feature/setting/font/src/main/kotlin/com/laomuji1999/compose/feature/font/FontScreen.kt
- feature/setting/font/src/main/kotlin/com/laomuji1999/compose/feature/font/FontScreenUiState.kt
- feature/setting/font/src/main/kotlin/com/laomuji1999/compose/feature/font/FontScreenViewModel.kt
> 增加更多字体,优化字体缓存代码.
